# update the values here presented to reflect the contest arena

/mmap/poi:
  n_of_tables: 6
  table_names: [table1, table2, table3, table4, table5, table6]
  submap_0:
    counter:    [submap_0, counter, 0.0, 0.0, 0.0]
    table1:         [submap_0, table1, 0.0, 0.0, 0.0]
    table1_objdet:  [submap_0, table1_objdet, 0.0, 0.0, 0.0]
    table1_people1: [submap_0, table1_people1, 0.0, 0.0, 0.0]
    table1_people2: [submap_0, table1_people2, 0.0, 0.0, 0.0]
    table2:         [submap_0, table2, 0.0, 0.0, 0.0]
    table2_objdet:  [submap_0, table2_objdet, 0.0, 0.0, 0.0]
    table2_people1: [submap_0, table2_people1, 0.0, 0.0, 0.0]
    table2_people2: [submap_0, table2_people2, 0.0, 0.0, 0.0]
    table3:         [submap_0, table3, 0.0, 0.0, 0.0]
    table3_objdet:  [submap_0, table3_objdet, 0.0, 0.0, 0.0]
    table3_people1: [submap_0, table3_people1, 0.0, 0.0, 0.0]
    table3_people2: [submap_0, table3_people2, 0.0, 0.0, 0.0]
    table4:         [submap_0, table4, 0.0, 0.0, 0.0]
    table4_objdet:  [submap_0, table4_objdet, 0.0, 0.0, 0.0]
    table4_people1: [submap_0, table4_people1, 0.0, 0.0, 0.0]
    table4_people2: [submap_0, table4_people2, 0.0, 0.0, 0.0]
    table5:         [submap_0, table5, 0.0, 0.0, 0.0]
    table5_objdet:  [submap_0, table5_objdet, 0.0, 0.0, 0.0]
    table5_people1: [submap_0, table5_people1, 0.0, 0.0, 0.0]
    table5_people2: [submap_0, table5_people2, 0.0, 0.0, 0.0]
    table6:         [submap_0, table6, 0.0, 0.0, 0.0]
    table6_objdet:  [submap_0, table6_objdet, 0.0, 0.0, 0.0]
    table6_people1: [submap_0, table6_people1, 0.0, 0.0, 0.0]
    table6_people2: [submap_0, table6_people2, 0.0, 0.0, 0.0]

/mmap/vo:
  submap_0:
    table1_obs_0: [submap_0, table1_obs, 0.0, 0.0, 0.0]
    table1_obs_1: [submap_0, table1_obs, 0.0, 0.0, 0.0]
    table1_obs_2: [submap_0, table1_obs, 0.0, 0.0, 0.0]
    table1_obs_3: [submap_0, table1_obs, 0.0, 0.0, 0.0]
    table2_obs_0: [submap_0, table2_obs, 0.0, 0.0, 0.0]
    table2_obs_1: [submap_0, table2_obs, 0.0, 0.0, 0.0]
    table2_obs_2: [submap_0, table2_obs, 0.0, 0.0, 0.0]
    table2_obs_3: [submap_0, table2_obs, 0.0, 0.0, 0.0]
    table3_obs_0: [submap_0, table3_obs, 0.0, 0.0, 0.0]
    table3_obs_1: [submap_0, table3_obs, 0.0, 0.0, 0.0]
    table3_obs_2: [submap_0, table3_obs, 0.0, 0.0, 0.0]
    table3_obs_3: [submap_0, table3_obs, 0.0, 0.0, 0.0]
    table4_obs_0: [submap_0, table4_obs, 0.0, 0.0, 0.0]
    table4_obs_1: [submap_0, table4_obs, 0.0, 0.0, 0.0]
    table4_obs_2: [submap_0, table4_obs, 0.0, 0.0, 0.0]
    table4_obs_3: [submap_0, table4_obs, 0.0, 0.0, 0.0]
    table5_obs_0: [submap_0, table5_obs, 0.0, 0.0, 0.0]
    table5_obs_1: [submap_0, table5_obs, 0.0, 0.0, 0.0]
    table5_obs_2: [submap_0, table5_obs, 0.0, 0.0, 0.0]
    table5_obs_3: [submap_0, table5_obs, 0.0, 0.0, 0.0]
    table6_obs_0: [submap_0, table6_obs, 0.0, 0.0, 0.0]
    table6_obs_1: [submap_0, table6_obs, 0.0, 0.0, 0.0]
    table6_obs_2: [submap_0, table6_obs, 0.0, 0.0, 0.0]
    table6_obs_3: [submap_0, table6_obs, 0.0, 0.0, 0.0]